/* Italian translations. Keep numbered placeholders and platform markup intact. */
(function (root) {
	const catalog = {
		language: "it",
		locale: "it-IT",
		messages: {
			"Gotify notifications:": "Notifiche Gotify:",
			"Enable notifications to your Gotify server.": "Abilita le notifiche sul tuo server Gotify.",
			"Gotify server URL:": "URL del server Gotify:",
			"Include any reverse proxy path, for example https://example.com/gotify.": "Includi il percorso del proxy inverso, ad esempio https://example.com/gotify.",
			"Application token:": "Token dell’applicazione:",
			"Create an application in the Gotify web UI and copy its token.": "Crea un’applicazione nell’interfaccia web di Gotify e copia il suo token.",
			"Message priority:": "Priorità del messaggio:",
			"Default: 5. Your Gotify client uses priority to control notification sounds and visibility.": "Predefinita: 5. Il client Gotify usa la priorità per controllare suoni e visibilità delle notifiche.",
			"Gotify priority must be a whole number.": "La priorità Gotify deve essere un numero intero.",
			"Invalid Gotify server URL. Provide an HTTP or HTTPS URL.": "URL del server Gotify non valido. Fornisci un URL HTTP o HTTPS.",
			"Invalid Gotify server URL. Use an HTTP or HTTPS URL without credentials, query parameters, or a fragment.": "URL del server Gotify non valido. Usa un URL HTTP o HTTPS senza credenziali, parametri di query o frammenti.",
			"No Gotify application token provided.": "Nessun token dell’applicazione Gotify fornito.",
			"Gotify priority must be an integer.": "La priorità Gotify deve essere un numero intero.",
			"Gotify messages must be strings or notification objects.": "I messaggi Gotify devono essere stringhe o oggetti di notifica.",
			"Gotify messages must not be empty.": "I messaggi Gotify non devono essere vuoti.",
			"Failed to send Gotify notification": "Invio della notifica Gotify non riuscito",

			"1 day": "1 giorno",
			"1 hr": "1 ora",
			"No chat ID provided for Telegram controller": "Nessun ID chat fornito per il controller Telegram",
			"Telegram token has not been configured for the bot": "Il token Telegram del bot non è stato configurato",
			"Failed to get telegram updates": "Impossibile ottenere gli aggiornamenti Telegram",
			"Provided message is not a string": "Il messaggio fornito non è una stringa",
			"Failed to send telegram message": "Invio del messaggio Telegram non riuscito",
			"There are no accounts available for redeeming codes.": "Non ci sono account disponibili per riscattare codici.",
			"Please select the account you want to redeem the code for:": "Seleziona l'account per cui vuoi riscattare il codice:",
			"Please enter the code you want to redeem:": "Inserisci il codice che vuoi riscattare:",
			"Failed to redeem code: {0}": "Riscatto del codice non riuscito: {0}",
			"Successfully redeemed code: {0}": "Codice riscattato: {0}",
			"Send a test notification to verify platform functionality": "Invia una notifica di prova per verificare il funzionamento della piattaforma",
			"Custom message for the test notification": "Messaggio personalizzato per la notifica di prova",
			"This command can only be used through Discord or Telegram platforms.": "Questo comando può essere usato solo tramite Discord o Telegram.",
			"Manual test notification triggered via command": "Notifica di prova manuale richiesta tramite comando",
			"Manual test triggered via Discord bot: {0}": "Prova manuale richiesta tramite il bot Discord: {0}",
			"🧪 **Manual Test Notification**\n\n{0}\n\n🔧 **Test Type:** Manual\n🕒 **Triggered At:** {1}\n🤖 **Platform:** Discord Bot": "🧪 **Notifica di prova manuale**\n\n{0}\n\n🔧 **Tipo di prova:** Manuale\n🕒 **Richiesta alle:** {1}\n🤖 **Piattaforma:** Bot Discord",
			"✅ Test notification sent successfully!": "✅ Notifica di prova inviata!",
			"Failed to send test notification: {0}": "Invio della notifica di prova non riuscito: {0}",
			"❌ Failed to send test notification: {0}": "❌ Invio della notifica di prova non riuscito: {0}",
			"No webhook URL provided": "Nessun URL webhook fornito",
			"Provided message is not an object": "Il messaggio fornito non è un oggetto",
			"Failed to send webhook message": "Invio del messaggio webhook non riuscito",
			"No bot ID provided for Discord controller": "Nessun ID bot fornito per il controller Discord",
			"Discord token has not been configured for the bot": "Il token Discord del bot non è stato configurato",
			"Invalid Discord message provided": "Il messaggio Discord fornito non è valido",
			"Failed to send message to Discord channel": "Invio del messaggio al canale Discord non riuscito",
			"Cleaning up {0} stale command(s): {1}": "Rimozione di {0} comandi obsoleti: {1}",
			"Adding {0} new command(s): {1}": "Aggiunta di {0} nuovi comandi: {1}",
			"Syncing {0} application command(s)...": "Sincronizzazione di {0} comandi dell'applicazione...",
			"Successfully registered {0} application command(s).": "Registrazione di {0} comandi dell'applicazione completata.",
			"Failed to register application commands": "Registrazione dei comandi dell'applicazione non riuscita",
			"No ID provided for Platform.": "Nessun ID fornito per la piattaforma.",
			"Invalid ID must be a number.": "ID non valido: deve essere un numero.",
			"Invalid URL provided for Webhook Platform.": "L'URL fornito per la piattaforma webhook non è valido.",
			"Send method not implemented by the Platform.": "Il metodo send non è implementato dalla piattaforma.",
			"No type provided for webhook message preparation": "Nessun tipo fornito per la preparazione del messaggio webhook",
			"Invalid message data provided.": "I dati del messaggio forniti non sono validi.",
			"Invalid type provided.": "Il tipo fornito non è valido.",
			"This method must be implemented at the derived platofrm": "Questo metodo deve essere implementato nella piattaforma derivata",
			"Unrecognized identifier type.": "Tipo di identificatore non riconosciuto.",
			"Invalid platform type provided.": "Il tipo di piattaforma fornito non è valido.",
			"**{0}**'s Diary": "Diario di **{0}**",
			"Primo income is decreased by {0}% compared to last month.": "Le primogemme ottenute sono diminuite del {0}% rispetto al mese scorso.",
			"**Obtained This Month**": "**Ottenuti questo mese**",
			"Primos: {0}\nMora: {1}": "Primogemme: {0}\nMora: {1}",
			"**Obtained Last Month**": "**Ottenuti il mese scorso**",
			"**Current Month\nBreakdown**": "**Riepilogo del\nmese corrente**",
			"**Last Month\nBreakdown**": "**Riepilogo del\nmese scorso**",
			"HoyoLab Diary - {0}": "Diario HoYoLAB - {0}",
			"Jades income is decreased by {0}% compared to last month.": "Le giade ottenute sono diminuite del {0}% rispetto al mese scorso.",
			"Jades: {0}\nPass: {1}": "Giade: {0}\nPass: {1}",
			"Check your total amount of incoming monthly resources.": "Controlla il totale delle risorse ottenute nel mese.",
			"The game you want to check diary for.": "Il gioco di cui vuoi consultare il diario.",
			"Select the account you want to check diary for.": "Seleziona l'account di cui vuoi consultare il diario.",
			"This account does not belong to the selected game.": "Questo account non appartiene al gioco selezionato.",
			"Something went wrong.": "Si è verificato un errore.",
			"Status: {0}\nRemaining Time: {1}": "Stato: {0}\nTempo rimanente: {1}",
			"Expedition Reminder": "Promemoria spedizioni",
			"Current expedition status": "Stato attuale delle spedizioni",
			"{0}: {1} - Remaining Time: {2}": "{0}: {1} - Tempo rimanente: {2}",
			"UID: {0}": "UID: {0}",
			"Username: {0}": "Nome utente: {0}",
			"Region: {0}": "Regione: {0}",
			"Check the status of your expedition.": "Controlla lo stato delle tue spedizioni.",
			"The game you want to check expeditions for.": "Il gioco di cui vuoi controllare le spedizioni.",
			"There are no accounts available for checking expeditions or the game is not supported.": "Non ci sono account disponibili per controllare le spedizioni oppure il gioco non è supportato.",
			"Please specify a game. Supported games are: {0}": "Specifica un gioco. Giochi supportati: {0}",
			"Invalid game. Supported games are: {0}": "Gioco non valido. Giochi supportati: {0}",
			"You don't have any accounts for this game.": "Non hai account per questo gioco.",
			"No expedition data found for this type of account.": "Nessun dato sulle spedizioni trovato per questo tipo di account.",
			"No expedition data found for this type of account": "Nessun dato sulle spedizioni trovato per questo tipo di account",
			"Redeem provided codes for the specified game.": "Riscatta i codici forniti per il gioco specificato.",
			"The game you want to redeem codes for.": "Il gioco per cui vuoi riscattare i codici.",
			"Select the account you want to check notes for.": "Seleziona l'account di cui vuoi controllare le note.",
			"The code you want to redeem. (Only one code per command)": "Il codice da riscattare. (Un solo codice per comando)",
			"Please specify a game.": "Specifica un gioco.",
			"No game provided. Supported games are: {0}": "Nessun gioco specificato. Giochi supportati: {0}",
			"Please specify a code.": "Specifica un codice.",
			"No code provided.": "Nessun codice fornito.",
			"Manually run check-in for all games or a specific game.": "Esegui manualmente il check-in per tutti i giochi o per un gioco specifico.",
			"The game you want to check-in for. Leave empty to check-in for all games.": "Il gioco per cui fare il check-in. Lascia vuoto per tutti i giochi.",
			"All Games": "Tutti i giochi",
			"No active game accounts found.": "Nessun account di gioco attivo trovato.",
			"Check-in failed": "Check-in non riuscito",
			"All accounts have already checked in today or no accounts found.": "Tutti gli account hanno già effettuato il check-in oggi oppure non ci sono account.",
			"Today's Reward": "Ricompensa di oggi",
			"Total Sign-ins": "Check-in totali",
			"Manual Check-In ({0}/{1})": "Check-in manuale ({0}/{1})",
			"❌ Check-In Errors": "❌ Errori di check-in",
			"🎮 **{0}** Manual Check-In": "🎮 **{0}** Check-in manuale",
			"🌍 **Region:** {0}": "🌍 **Regione:** {0}",
			"🏆 **Rank:** {0}": "🏆 **Livello:** {0}",
			"🎁 **Today's Reward:** {0} x{1}": "🎁 **Ricompensa di oggi:** {0} x{1}",
			"📅 **Total Sign-ins:** {0}": "📅 **Check-in totali:** {0}",
			"📝 **Result:** {0}": "📝 **Risultato:** {0}",
			"✅ Successfully checked in for {0} account(s):": "✅ Check-in completato per {0} account:",
			"❌ Failed for {0} game(s):": "❌ Operazione non riuscita per {0} giochi:",
			"🎯 Tasks Claimed": "🎯 Missioni riscosse",
			"💰 Points Earned": "💰 Punti ottenuti",
			"+{0} pts": "+{0} punti",
			"🆓 Free Items Claimed": "🆓 Oggetti gratuiti riscossi",
			"🎁 Items Exchanged": "🎁 Oggetti scambiati",
			"• {0} (-{1} pts)": "• {0} (-{1} punti)",
			"✅ Codes Redeemed": "✅ Codici riscattati",
			"🎫 Codes Obtained": "🎫 Codici ottenuti",
			"💎 Current Points": "💎 Punti attuali",
			"{0} pts": "{0} punti",
			"🔧 Hilichurl Machine Workshop": "🔧 Officina meccanica degli Hilichurl",
			"Successfully ran Hilichurl Workshop automation for Genshin Impact!": "Automazione dell'officina degli Hilichurl per Genshin Impact completata!",
			"No new activity for Genshin Impact.": "Nessuna nuova attività per Genshin Impact.",
			"Manually run Hilichurl Machine Workshop automation for Genshin Impact.": "Esegui manualmente l'automazione dell'officina meccanica degli Hilichurl per Genshin Impact.",
			"No Genshin Impact accounts found.": "Nessun account Genshin Impact trovato.",
			"Hilichurl Workshop is not available.": "L'officina degli Hilichurl non è disponibile.",
			"Running Hilichurl for Genshin - {0}": "Esecuzione di Hilichurl per Genshin - {0}",
			"Unknown error": "Errore sconosciuto",
			"Hilichurl automation failed": "Automazione di Hilichurl non riuscita",
			"No Genshin accounts available for Hilichurl Workshop.": "Nessun account Genshin disponibile per l'officina degli Hilichurl.",
			"❌ Errors": "❌ Errori",
			"GI - {0}: {1} pts": "GI - {0}: {1} punti",
			"{0} Server - {1}": "Server {0} - {1}",
			"Current Stamina:": "Energia attuale:",
			"\nFull in:\n{0}": "\nAl massimo tra:\n{0}",
			"HoyoLab Notes - {0}": "Note HoYoLAB - {0}",
			"Stored Attendance: {0}": "Punti incontro accumulati: {0}",
			"Refresh in: {0}": "Ripristino tra: {0}",
			"Stored Attendance": "Punti incontro accumulati",
			"Weekly Boss:": "Boss settimanali:",
			"Realm Currency": "Valuta del regno",
			"\nCapped in: {0}": "\nAl limite tra: {0}",
			"Expedition Status": "Stato delle spedizioni",
			"**Account {0}** - {1}": "**Account {0}** - {1}",
			"Weekly Status:": "Stato settimanale:",
			"Boss: {0}/{1}": "Boss: {0}/{1}",
			"\nSimulated Universe: {0}/{1}": "\nUniverso simulato: {0}/{1}",
			"\nDivergent Universe: {0}/{1}": "\nUniverso divergente: {0}/{1}",
			"Shop Status": "Stato del negozio",
			"Bounty Commission: {0}/{1}": "Incarichi taglia: {0}/{1}",
			"\nSurvey Points: {0}/{1}": "\nPunti indagine: {0}/{1}",
			"Scratch Card": "Gratta e vinci",
			"Current Stamina: {0}/{1}": "Energia attuale: {0}/{1}",
			"\nFull in: {0}": "\nAl massimo tra: {0}",
			"Account {0} - {1}": "Account {0} - {1}",
			"Dailies: {0}/{1}": "Attività giornaliere: {0}/{1}",
			"Weekly Boss Chance Remaining: {0}/{1}": "Tentativi boss settimanali rimanenti: {0}/{1}",
			"Survey Points: {0}/{1}": "Punti indagine: {0}/{1}",
			"Shop Status: {0}": "Stato del negozio: {0}",
			"Howl Scratch Card: {0}": "Gratta e vinci di Howl: {0}",
			"Check your HoyoLab notes.": "Controlla le tue note HoYoLAB.",
			"The game you want to check notes for.": "Il gioco di cui vuoi controllare le note.",
			"Select the account you want to check notes for. If not specified, will check all accounts.": "Seleziona l'account di cui controllare le note. Se omesso, verranno controllati tutti gli account.",
			"There are no accounts available for checking notes.": "Non ci sono account disponibili per controllare le note.",
			"Invalid game specified. Supported games are: {0}": "Il gioco specificato non è valido. Giochi supportati: {0}",
			"You don't have any accounts for that game.": "Non hai account per quel gioco.",
			"This account has no notes to check.": "Questo account non ha note da controllare.",
			"🎰 Lottery Draws": "🎰 Estrazioni della lotteria",
			"🐾 Traveling Mimo": "🐾 Mimo in viaggio",
			"Successfully ran Mimo automation for {0}!": "Automazione di Mimo per {0} completata!",
			"No new activity for {0}.": "Nessuna nuova attività per {0}.",
			"Manually run Traveling Mimo automation for all games or a specific game.": "Esegui manualmente l'automazione di Mimo in viaggio per tutti i giochi o per un gioco specifico.",
			"The game you want to run Mimo for. Leave empty for all games.": "Il gioco per cui eseguire Mimo. Lascia vuoto per tutti i giochi.",
			"Invalid game specified. Supported games are: Star Rail, ZZZ": "Il gioco specificato non è valido. Giochi supportati: Star Rail, ZZZ",
			"Mimo not supported": "Mimo non supportato",
			"Running Mimo for {0} - {1}": "Esecuzione di Mimo per {0} - {1}",
			"Mimo automation failed": "Automazione di Mimo non riuscita",
			"No accounts found with Mimo enabled.": "Nessun account trovato con Mimo abilitato.",
			"{0} - {1}: {2} pts": "{0} - {1}: {2} punti",
			"Howl's News Stand": "Edicola di Howl",
			"You haven't scratched the card at Howl's News Stand yet!": "Non hai ancora usato il gratta e vinci all'edicola di Howl!",
			"📰 Howl's News Stand": "📰 Edicola di Howl",
			"Reminds you if you haven't scratched the card at Howl's News Stand.": "Ti ricorda di usare il gratta e vinci all'edicola di Howl.",
			"This check if all accounts successfully checked in today before daily reset": "Controlla che tutti gli account abbiano effettuato il check-in prima del ripristino giornaliero",
			"No active accounts found for HoyoLab": "Nessun account attivo trovato per HoYoLAB",
			"This will check your current shop status and will fire a notification if your shop has finished selling.": "Controlla lo stato del negozio e invia una notifica quando ha finito di vendere.",
			"No active accounts found to run shop status for.": "Nessun account attivo trovato per controllare il negozio.",
			"Your shop has finished selling videos!": "Il tuo negozio ha finito di vendere video!",
			"🛒 Shop Status": "🛒 Stato del negozio",
			"UID: {0} {1}": "UID: {0} {1}",
			"Update cookie for all accounts": "Aggiorna i cookie di tutti gli account",
			"obj must be an object to receive as params": "obj deve essere un oggetto da ricevere come parametro",
			"message must be a string": "message deve essere una stringa",
			"- args: {0}": "- argomenti: {0}",
			"cause: {0} {1}": "causa: {0} {1}",
			"(no message)": "(nessun messaggio)",
			"(no stack)": "(nessuno stack)",
			"The account does not exist": "L'account non esiste",
			"The provided cookie is either invalid or expired.": "Il cookie fornito non è valido oppure è scaduto.",
			"Cannot get data after more than 30 accounts per cookie per day.": "Non è possibile ottenere dati per più di 30 account per cookie al giorno.",
			"API system is busy, please try again later.": "Il sistema API è occupato, riprova più tardi.",
			"The code has expired": "Il codice è scaduto",
			"The code is invalid": "Il codice non è valido",
			"Redemption is in cooldown": "È necessario attendere prima del prossimo riscatto",
			"The code has been used": "Il codice è già stato usato",
			"A captcha challenge was requested. Please solve it and try again.": "È stato richiesto un captcha. Risolvilo e riprova.",
			"Invalid region. Use 'ASIA', 'EU', or 'AMERICA'": "Regione non valida. Usa 'ASIA', 'EU' o 'AMERICA'",
			"Invalid offset": "Offset non valido",
			"Unrecognized offset - make sure to use offset in minutes": "Offset non riconosciuto: usa un offset in minuti",
			"Unrecognized time unit {0}": "Unità di tempo non riconosciuta: {0}",
			"Executed for account {0} in region {1}": "Eseguito per l'account {0} nella regione {1}",
			"Current: {0}/{1}": "Attuale: {0}/{1}",
			"Recovery Time: {0}": "Tempo di recupero: {0}",
			"Reserve Stamina: {0}": "Energia di riserva: {0}",
			"Check your specified game stamina": "Controlla l'energia del gioco specificato",
			"The game you want to check stamina for.": "Il gioco di cui vuoi controllare l'energia.",
			"There are no accounts available for checking stamina.": "Non ci sono account disponibili per controllare l'energia.",
			"No stamina data found for this type of account": "Nessun dato sull'energia trovato per questo tipo di account",
			"Cannot have both a blacklist and a whitelist for crons": "Non è possibile impostare sia blacklist sia whitelist per i cron",
			"Initialized {0} cron jobs": "Inizializzati {0} processi cron",
			"Run daily check-in every day at midnight or your specified time": "Esegui il check-in ogni giorno a mezzanotte o all'orario specificato",
			"All accounts either signed in or failed to sign in": "Per tutti gli account il check-in è stato completato oppure non è riuscito",
			"No accounts to run check-in for": "Nessun account per cui effettuare il check-in",
			"HoyoLab Auto Check-In ({0}/{1}) Executed": "Check-in automatico HoYoLAB ({0}/{1}) eseguito",
			"🎮 **{0}** Daily Check-In": "🎮 **{0}** Check-in giornaliero",
			"This cron will check your Tea Pot Realm currency and notify you if it's full": "Questo cron controlla la valuta del regno della Serenteiera e ti avvisa quando è al massimo",
			"No active accounts to run the cron": "Nessun account attivo per eseguire il cron",
			"Your realm currency is full!": "La tua valuta del regno è al massimo!",
			"Current Realm Currency": "Valuta del regno attuale",
			"💰 Realm Currency": "💰 Valuta del regno",
			"Check for your stamina and notify you when it's within the set threshold.": "Controlla l'energia e ti avvisa quando raggiunge la soglia impostata.",
			"No active accounts found to run stamina check for.": "Nessun account attivo trovato per controllare l'energia.",
			"Your stamina is full!": "La tua energia è al massimo!",
			"Your stamina is within the set threshold!": "La tua energia ha raggiunto la soglia impostata!",
			"Stamina Reminder": "Promemoria energia",
			"Recovery Time": "Tempo di recupero",
			"📢 Stamina Reminder, {0}": "📢 Promemoria energia, {0}",
			"🎮 **Game**: {0}": "🎮 **Gioco**: {0}",
			"🆔 **UID**: {0} {1}": "🆔 **UID**: {0} {1}",
			"🌍 **Region**: {0}": "🌍 **Regione**: {0}",
			"🔋 **Stamina**: {0}/{1}": "🔋 **Energia**: {0}/{1}",
			"🕒 **Recovery Time**: {0}": "🕒 **Tempo di recupero**: {0}",
			"No platforms configured! Exiting.": "Nessuna piattaforma configurata! Uscita.",
			"Loading configuration data": "Caricamento della configurazione",
			"Loaded {0} configuration entries": "Caricate {0} voci di configurazione",
			"No accounts configured! Exiting.": "Nessun account configurato! Uscita.",
			"Skipping {0} account (inactive)": "Account {0} ignorato (inattivo)",
			"Skipping {0} platform (inactive)": "Piattaforma {0} ignorata (inattiva)",
			"Initialize completed ({0}ms)": "Inizializzazione completata ({0}ms)",
			"Unhandled promise rejection": "Promise rifiutata senza gestione dell'errore",
			"Command name must be a string and not empty": "Il nome del comando deve essere una stringa non vuota",
			"Command parameters are not valid JSON": "I parametri del comando non sono JSON valido",
			"Failed to compile code for {0}": "Compilazione del codice per {0} non riuscita",
			"Failed to compile code": "Compilazione del codice non riuscita",
			"No description provided": "Nessuna descrizione fornita",
			"Unsupported parameter type: {0} for {1}": "Tipo di parametro non supportato: {0} per {1}",
			"No commands loaded": "Nessun comando caricato",
			"No configuration data found": "Nessun dato di configurazione trovato",
			"Duplicate command name found": "Trovato un nome di comando duplicato",
			"Invalid command name": "Nome del comando non valido",
			"No command name specified": "Nessun nome di comando specificato",
			"Invalid argument array": "Array degli argomenti non valido",
			"Command not found": "Comando non trovato",
			"Command execution failed": "Esecuzione del comando non riuscita",
			"An error occurred while executing the command": "Si è verificato un errore durante l'esecuzione del comando",
			"(empty response)": "(risposta vuota)",
			"Invalid user identifier type": "Tipo di identificatore utente non valido",
			"Definitions must be provided as an array": "Le definizioni devono essere fornite come array",
			"Instance parent is not defined": "L'istanza padre non è definita",
			"Got instance {0} init error - skipped": "Errore di inizializzazione dell'istanza Got {0}: ignorata",
			"Instance is not available due to initialization error": "L'istanza non è disponibile a causa di un errore di inizializzazione",
			"Requested parent instance does not exist": "L'istanza padre richiesta non esiste",
			"loadData() must be implemented in the child class": "loadData() deve essere implementato nella classe derivata",
			"Check for ongoing expeditions every 30 minutes and send a notification if all expeditions are completed.": "Controlla le spedizioni ogni 30 minuti e invia una notifica se sono tutte completate.",
			"No active accounts found to run expedition check for.": "Nessun account attivo trovato per controllare le spedizioni.",
			"All expeditions are completed!": "Tutte le spedizioni sono completate!",
			"📢 Expedition Reminder, All Expeditions are Completed!": "📢 Promemoria spedizioni, tutte le spedizioni sono completate!",
			"Dailies Reminder": "Promemoria attività giornaliere",
			"Don't forget to complete your dailies!": "Non dimenticare di completare le attività giornaliere!",
			"Completed Dailies": "Attività giornaliere completate",
			"Current Stamina": "Energia attuale",
			"📢 Dailies Reminder, Don't Forget to Do Your Dailies!": "📢 Promemoria attività giornaliere, non dimenticare di completarle!",
			"📅 **Completed Dailies**: {0}/{1}": "📅 **Attività giornaliere completate**: {0}/{1}",
			"🔋 **Current Stamina**: {0}/{1} ({2})": "🔋 **Energia attuale**: {0}/{1} ({2})",
			"Reminds you to complete your dailies.": "Ti ricorda di completare le attività giornaliere.",
			"No platforms configured for test notifications": "Nessuna piattaforma configurata per le notifiche di prova",
			"Sending test notifications to all configured platforms": "Invio delle notifiche di prova a tutte le piattaforme configurate",
			"Successfully sent test notification to {0} (ID: {1})": "Notifica di prova inviata a {0} (ID: {1})",
			"Failed to send test notification to {0} (ID: {1}): {2}": "Invio della notifica di prova a {0} (ID: {1}) non riuscito: {2}",
			"Test notifications completed: {0} successful, {1} failed": "Notifiche di prova completate: {0} riuscite, {1} non riuscite",
			"Discord bot (ID: {0}) is connected and ready": "Il bot Discord (ID: {0}) è connesso e pronto",
			"🔥 HoyoLab Auto - Test Notification": "🔥 HoyoLab Auto - Notifica di prova",
			"This is a test notification to confirm that the webhook is working properly.": "Questa è una notifica di prova per verificare che il webhook funzioni correttamente.",
			"✅ Connected": "✅ Connesso",
			"Local Time": "Ora locale",
			"HoyoLab Auto Test System": "Sistema di prova HoyoLab Auto",
			"🚀 **HoyoLab Auto Started Successfully!**": "🚀 **HoyoLab Auto avviato correttamente!**",
			"🔥 *HoyoLab Auto \\- Test Notification*\n\n": "🔥 *HoyoLab Auto \\- Notifica di prova*\n\n",
			"This is a test notification to confirm that the Telegram bot is working properly\\.\n\n": "Questa è una notifica di prova per verificare che il bot Telegram funzioni correttamente\\.\n\n",
			"✅ *Status:* Connected\n": "✅ *Stato:* Connesso\n",
			"🕒 *Local Time:* {0}\n": "🕒 *Ora locale:* {0}\n",
			"🤖 *Platform:* Telegram Bot\n\n": "🤖 *Piattaforma:* Bot Telegram\n\n",
			"🚀 *HoyoLab Auto Started Successfully\\!*": "🚀 *HoyoLab Auto avviato correttamente\\!*",
			"Unknown platform type: {0}": "Tipo di piattaforma sconosciuto: {0}",
			"Failed to send test notification to {0}": "Invio della notifica di prova a {0} non riuscito",
			"undefined platform": "piattaforma non definita",
			"Manual test notification triggered": "Notifica di prova manuale richiesta",
			"🧪 HoyoLab Auto - Manual Test": "🧪 HoyoLab Auto - Prova manuale",
			"Test Type": "Tipo di prova",
			"Triggered At": "Richiesta alle",
			"HoyoLab Auto Manual Test": "Prova manuale HoyoLab Auto",
			"🧪 **Manual Test Notification**": "🧪 **Notifica di prova manuale**",
			"🧪 *HoyoLab Auto \\- Manual Test*\n\n": "🧪 *HoyoLab Auto \\- Prova manuale*\n\n",
			"🔧 *Test Type:* Manual\n": "🔧 *Tipo di prova:* Manuale\n",
			"🕒 *Triggered At:* {0}\n": "🕒 *Richiesta alle:* {0}\n",
			"🤖 *Platform:* Telegram Bot": "🤖 *Piattaforma:* Bot Telegram",
			"Manual test triggered for Discord bot (ID: {0}): {1}": "Prova manuale richiesta per il bot Discord (ID: {0}): {1}",
			"Manual test not supported for platform type: {0}": "Prova manuale non supportata per il tipo di piattaforma: {0}",
			"Failed to send manual test notification to {0}": "Invio della notifica di prova manuale a {0} non riuscito",
			"This will run the Hilichurl Machine Workshop automation for Genshin Impact - completing tasks, claiming rewards, and exchanging for Primogems.": "Esegue l'automazione dell'officina meccanica degli Hilichurl per Genshin Impact: completa missioni, riscuote ricompense ed effettua scambi per primogemme.",
			"Applying {0}s jitter before starting...": "Attesa casuale di {0}s prima di iniziare...",
			"No active Genshin accounts found": "Nessun account Genshin attivo trovato",
			"Hilichurl method not found on Genshin platform": "Metodo Hilichurl non trovato sulla piattaforma Genshin",
			"({0}) Hilichurl check disabled, skipping": "({0}) Controllo Hilichurl disabilitato, ignorato",
			"({0}) Running Hilichurl automation...": "({0}) Esecuzione dell'automazione di Hilichurl...",
			"({0}) Genshin Impact: No new Hilichurl activity.": "({0}) Genshin Impact: nessuna nuova attività di Hilichurl.",
			"🎫 Codes Obtained (Not Auto-Redeemed)": "🎫 Codici ottenuti (non riscattati automaticamente)",
			"⏰ Next Primogem Restock": "⏰ Prossimo rifornimento di primogemme",
			"🔧 Hilichurl Machine Workshop - Genshin Impact": "🔧 Officina meccanica degli Hilichurl - Genshin Impact",
			"Hilichurl Workshop Automation": "Automazione dell'officina degli Hilichurl",
			"🔧 *Hilichurl Machine Workshop* - Genshin Impact": "🔧 *Officina meccanica degli Hilichurl* - Genshin Impact",
			"Region: {0} | UID: {1}": "Regione: {0} | UID: {1}",
			"Player: {0}": "Giocatore: {0}",
			"🎯 Tasks Claimed: {0} (+{1} pts)": "🎯 Missioni riscosse: {0} (+{1} punti)",
			"🆓 Free Items: {0} claimed": "🆓 Oggetti gratuiti: {0} riscossi",
			"🎁 Items Exchanged: {0}": "🎁 Oggetti scambiati: {0}",
			"✅ Codes Redeemed: {0}": "✅ Codici riscattati: {0}",
			"🎫 Codes Obtained (Not Auto-Redeemed):": "🎫 Codici ottenuti (non riscattati automaticamente):",
			"💎 Current Points: {0}": "💎 Punti attuali: {0}",
			"({0}) Genshin Impact: Hilichurl automation completed.": "({0}) Genshin Impact: automazione di Hilichurl completata.",
			"Error running Hilichurl automation": "Errore durante l'esecuzione dell'automazione di Hilichurl",
			"Provided value must not be undefined": "Il valore fornito non deve essere undefined",
			"If provided, expiry must be a valid positive integer": "Se specificata, la scadenza deve essere un numero intero positivo valido",
			"Cannot use null or undefined as key": "Non è possibile usare null o undefined come chiave",
			"Cannot stringify a non-primitive value": "Non è possibile convertire in stringa un valore non primitivo",
			"Cache prefix keys cannot contain reserved characters": "Le chiavi del prefisso della cache non possono contenere caratteri riservati",
			"Cache prefix vaolues cannot contain reserved characters": "I valori del prefisso della cache non possono contenere caratteri riservati",
			"{0} days": "{0} giorni",
			"{0} hr": "{0} ore",
			"{0} min": "{0} min",
			"{0} sec": "{0} sec",
			"Text must be typeof string": "Il testo deve essere di tipo string",
			"Log level set to {0}": "Livello di log impostato su {0}",
			"No ID provided for HoyoLab.": "Nessun ID fornito per HoYoLAB.",
			"Invalid data provided for HoyoLab must be an array.": "I dati forniti per HoYoLAB non sono validi: devono essere un array.",
			"No accounts provided for {0}, please provide at least one account or disable the platform.": "Nessun account fornito per {0}: specifica almeno un account oppure disabilita la piattaforma.",
			"This cookie method is deprecated, please follow the new cookie guide again: https://gist.github.com/torikushiii/59eff33fc8ea89dbc0b2e7652db9d3fd": "Questo metodo per i cookie è obsoleto. Segui la nuova guida: https://gist.github.com/torikushiii/59eff33fc8ea89dbc0b2e7652db9d3fd",
			"Invalid check provided for HoyoLab expected boolean.": "Il valore check fornito per HoYoLAB non è valido: atteso un booleano.",
			"Invalid realm.check provided for HoyoLab expected boolean.": "Il valore realm.check fornito per HoYoLAB non è valido: atteso un booleano.",
			"Invalid realm.persistent provided for HoyoLab expected boolean.": "Il valore realm.persistent fornito per HoYoLAB non è valido: atteso un booleano.",
			"Invalid stamina object provided for HoyoLab.": "L'oggetto stamina fornito per HoYoLAB non è valido.",
			"Invalid stamina threshold provided for {0}. Maximum stamina is {1}.": "La soglia di energia fornita per {0} non è valida. L'energia massima è {1}.",
			"Invalid expedition.check provided for HoyoLab expected boolean.": "Il valore expedition.check fornito per HoYoLAB non è valido: atteso un booleano.",
			"Invalid expedition.persistent provided for HoyoLab expected boolean.": "Il valore expedition.persistent fornito per HoYoLAB non è valido: atteso un booleano.",
			"No ltoken_v2, ltuid_v2, or ltmid_v2 found in cookie.": "ltoken_v2, ltuid_v2 o ltmid_v2 non trovati nel cookie.",
			"No cookie_token_v2 or account_mid_v2 found in cookie for {0}. This will disable \"redeemCode\" functionality.": "cookie_token_v2 o account_mid_v2 non trovati nel cookie per {0}. La funzione \"redeemCode\" verrà disabilitata.",
			"Could not refresh the cookie for account {0}: {1}": "Impossibile aggiornare il cookie per l'account {0}: {1}",
			"HoYoLAB Cookie Refresh Restored": "Aggiornamento cookie HoYoLAB ripristinato",
			"HoYoLAB Cookie Refresh Failed": "Aggiornamento cookie HoYoLAB non riuscito",
			"Cookie refresh is working again for HoYoLAB account {0}.": "L'aggiornamento del cookie funziona di nuovo per l'account HoYoLAB {0}.",
			"Could not refresh the cookie for HoYoLAB account {0}. Automatic code redemption may stop when the current cookie is no longer valid.": "Impossibile aggiornare il cookie per l'account HoYoLAB {0}. Il riscatto automatico dei codici potrebbe interrompersi quando il cookie attuale non sarà più valido.",
			"Could not notify {0} ({1}) for HoYoLAB account {2}: {3}": "Impossibile notificare {0} ({1}) per l'account HoYoLAB {2}: {3}",
			"Account not found in platform.": "Account non trovato nella piattaforma.",
			"Cannot have both a whitelist and blacklist.": "Non è possibile impostare sia whitelist sia blacklist.",
			"No active accounts found for this type of game.": "Nessun account attivo trovato per questo tipo di gioco.",
			"Redeem code functionality is currently disabled for this account.": "Il riscatto dei codici è attualmente disabilitato per questo account.",
			"Invalid UID provided for getAccountById expected string.": "L'UID fornito a getAccountById non è valido: attesa una stringa.",
			"Invalid type or code provided for HoyoError.": "Tipo o codice fornito a HoyoError non valido.",
			"This method is not implemented by the derived class.": "Questo metodo non è implementato dalla classe derivata.",
			"No stoken configured": "Nessuno stoken configurato",
			"Failed to update cookie": "Aggiornamento del cookie non riuscito",
			"Invalid response": "Risposta non valida",
			"Missing tokens in response": "Token mancanti nella risposta",
			"Failed to create platform {0}.": "Creazione della piattaforma {0} non riuscita.",
			"API returned malformed data": "L'API ha restituito dati malformati",
			"API returned non-200 status code": "L'API ha restituito un codice di stato diverso da 200",
			"Expired or invalid code": "Codice scaduto o non valido",
			"{0} - Redeemed": "{0} - Riscattato",
			"Redeem this code via the in-game exchange center.": "Riscatta questo codice tramite il centro scambi nel gioco.",
			"Redeem this code from the in-game Exchange menu.": "Riscatta questo codice dal menu Scambi nel gioco.",
			"Redeem this code from within the game client.": "Riscatta questo codice direttamente nel gioco.",
			"Unknown Game": "Gioco sconosciuto",
			"Manually Redeem Here": "Riscatta manualmente qui",
			"Code Successfully Redeemed!": "Codice riscattato!",
			"Code Redeem Failed! ({0})": "Riscatto del codice non riuscito! ({0})",
			"Code Found - Manual Redemption Required": "Codice trovato - Riscatto manuale necessario",
			"Redeem Online": "Riscatta online",
			"Unknown code redeem status received.": "Ricevuto uno stato di riscatto del codice sconosciuto.",
			"Unknown UID": "UID sconosciuto",
			"\nCode: {0}": "\nCodice: {0}",
			"\nRewards: {0}": "\nRicompense: {0}",
			"{0} Code Redeem": "Riscatto codici {0}",
			"Check and redeem codes for supported games from HoyoLab.": "Controlla e riscatta i codici HoYoLAB per i giochi supportati.",
			"No active accounts found": "Nessun account attivo trovato",
			"All accounts have redeem disabled": "Il riscatto è disabilitato per tutti gli account",
			"No codes found": "Nessun codice trovato",
			"No active accounts found for Tears of Themis": "Nessun account attivo trovato per Tears of Themis",
			"Already signed in today": "Check-in già effettuato oggi",
			"Today's Reward: {0} x{1}": "Ricompensa di oggi: {0} x{1}",
			"Failed to sign in": "Check-in non riuscito",
			"Failed to get sign info": "Impossibile ottenere le informazioni sul check-in",
			"Info returned non-zero retcode": "Le informazioni hanno restituito un retcode diverso da zero",
			"Failed to get awards data": "Impossibile ottenere i dati delle ricompense",
			"No awards data available (?)": "Nessun dato sulle ricompense disponibile (?)",
			"Successfully signed in": "Check-in effettuato",
			"No HoyoLab ID provided for TearsOfThemis controller": "Nessun ID HoYoLAB fornito per il controller TearsOfThemis",
			"No TearsOfThemis accounts provided": "Nessun account TearsOfThemis fornito",
			"Logged into account {0} [{1}] (Tears of Themis)": "Accesso effettuato all'account {0} [{1}] (Tears of Themis)",
			"Too Many Requests": "Troppe richieste",
			"Rate limited after {0} attempts, giving up": "Limite di richieste raggiunto dopo {0} tentativi, operazione interrotta",
			"Rate limited, retrying in {0}ms (attempt {1}/{2})": "Limite di richieste raggiunto, nuovo tentativo tra {0}ms (tentativo {1}/{2})",
			"Failed to fetch Hilichurl Workshop info": "Impossibile ottenere le informazioni sull'officina degli Hilichurl",
			"Hilichurl Workshop event not active for Genshin Impact": "L'evento officina degli Hilichurl non è attivo per Genshin Impact",
			"Failed to fetch Hilichurl tasks": "Impossibile ottenere le missioni di Hilichurl",
			"Failed to finish Hilichurl task": "Impossibile completare la missione di Hilichurl",
			"Failed to claim Hilichurl task reward": "Impossibile riscuotere la ricompensa della missione di Hilichurl",
			"Failed to fetch Hilichurl shop items": "Impossibile ottenere gli oggetti del negozio di Hilichurl",
			"Failed to exchange Hilichurl item": "Impossibile scambiare l'oggetto di Hilichurl",
			"Failed to get Hilichurl Workshop info": "Impossibile ottenere le informazioni sull'officina degli Hilichurl",
			"({0}) Starting Hilichurl Workshop automation - Current points: {1}": "({0}) Avvio dell'automazione dell'officina degli Hilichurl - Punti attuali: {1}",
			"({0}) Finished task: {1}": "({0}) Missione completata: {1}",
			"({0}) Claimed {1} points for: {2}": "({0}) Riscossi {1} punti per: {2}",
			"({0}) Claimed free item: {1}": "({0}) Oggetto gratuito riscosso: {1}",
			"({0}) Exchanged {1}{2}": "({0}) Scambiato {1}{2}",
			" for code: {0}": " per il codice: {0}",
			"({0}) Redeemed code: {1}": "({0}) Codice riscattato: {1}",
			"Failed to redeem code {0}: {1}": "Riscatto del codice {0} non riuscito: {1}",
			"({0}) Code obtained (not auto-redeemed): {1}": "({0}) Codice ottenuto (non riscattato automaticamente): {1}",
			"No primogem items found": "Nessun oggetto primogemme trovato",
			"This will run the Traveling Mimo automation for supported games (Star Rail, ZZZ) - completing tasks, claiming rewards, and exchanging for premium currency.": "Esegue l'automazione di Mimo in viaggio per i giochi supportati (Star Rail, ZZZ): completa missioni, riscuote ricompense ed effettua scambi per valuta premium.",
			"🐾 Traveling Mimo Failure - {0}": "🐾 Errore di Mimo in viaggio - {0}",
			"**Automation Failed:** {0}": "**Automazione non riuscita:** {0}",
			"Traveling Mimo Automation": "Automazione di Mimo in viaggio",
			"🐾 *Traveling Mimo Failure* - {0}": "🐾 *Errore di Mimo in viaggio* - {0}",
			"❌ *Error:* {0}": "❌ *Errore:* {0}",
			"({0}) {1}: No new Mimo activity.": "({0}) {1}: nessuna nuova attività di Mimo.",
			"⏰ Next Currency Restock": "⏰ Prossimo rifornimento di valuta",
			"🐾 Traveling Mimo - {0}": "🐾 Mimo in viaggio - {0}",
			"🐾 *Traveling Mimo* - {0}": "🐾 *Mimo in viaggio* - {0}",
			"🎰 Lottery Draws: {0}": "🎰 Estrazioni della lotteria: {0}",
			"❌ Errors:": "❌ Errori:",
			"({0}) {1}: Mimo automation completed.": "({0}) {1}: automazione di Mimo completata.",
			"Error running Mimo automation": "Errore durante l'esecuzione dell'automazione di Mimo",
			"No config file ({0}) was found. Please follow the setup instructions on https://github.com/torikushiii/hoyolab-auto?tab=readme-ov-file#installation \n{1}": "Nessun file di configurazione ({0}) trovato. Segui le istruzioni su https://github.com/torikushiii/hoyolab-auto?tab=readme-ov-file#installation \n{1}",
			"An error occurred when reading your configuration file ({0}). Please check and fix the following error:\n{1}": "Errore durante la lettura del file di configurazione ({0}). Controlla e correggi il seguente errore:\n{1}",
			"Unsupported file format. Only .js and .jsonc files are supported.": "Formato di file non supportato. Sono supportati solo file .js e .jsonc.",
			"{0} converted to {1}": "{0} convertito in {1}",
			"No config.js or config.jsonc file found in the directory.": "Nessun file config.js o config.jsonc trovato nella cartella.",
			"Weeklies Reminder": "Promemoria attività settimanali",
			"Don't forget to complete your weeklies!": "Non dimenticare di completare le attività settimanali!",
			"Resin Discount": "Sconto resina",
			"{0}/{1} Available": "{0}/{1} disponibili",
			"Weekly Boss": "Boss settimanali",
			"{0}/{1} Completed": "{0}/{1} completati",
			"Simulated Universe": "Universo simulato",
			"Divergent Universe": "Universo divergente",
			"Bounty Commission": "Incarichi taglia",
			"Survey Points": "Punti indagine",
			"📅 **Weeklies Reminder**": "📅 **Promemoria attività settimanali**",
			"👤 **Account**": "👤 **Account**",
			"- **UID**: {0}": "- **UID**: {0}",
			"- **Username**: {0}": "- **Nome utente**: {0}",
			"- **Region**: {0}": "- **Regione**: {0}",
			"📊 **Progress**": "📊 **Avanzamento**",
			"- **Resin Discount**: {0}/{1} Available": "- **Sconto resina**: {0}/{1} disponibili",
			"- **Weekly Boss**: {0}/{1} Completed": "- **Boss settimanali**: {0}/{1} completati",
			"- **Simulated Universe**: {0}/{1}": "- **Universo simulato**: {0}/{1}",
			"- **Divergent Universe**: {0}/{1}": "- **Universo divergente**: {0}/{1}",
			"- **Bounty Commission**: {0}/{1}": "- **Incarichi taglia**: {0}/{1}",
			"- **Survey Points**: {0}/{1}": "- **Punti indagine**: {0}/{1}",
			"Reminds you to complete your weeklies.": "Ti ricorda di completare le attività settimanali.",
			"No active accounts found for Honkai: Star Rail": "Nessun account attivo trovato per Honkai: Star Rail",
			"{0} already signed in today": "{0} ha già effettuato il check-in oggi",
			"({0}) {1} Today's Reward: {2} x{3}": "({0}) {1} Ricompensa di oggi: {2} x{3}",
			"You have successfully checked in today, Trailblazer~": "Check-in di oggi completato, Pioniere~",
			"You've already checked in today, Trailblazer~": "Hai già effettuato il check-in oggi, Pioniere~",
			"No HoyoLab ID provided for StarRail controller": "Nessun ID HoYoLAB fornito per il controller StarRail",
			"No StarRail accounts provided": "Nessun account StarRail fornito",
			"Failed to login to Honkai: Star Rail account": "Accesso all'account Honkai: Star Rail non riuscito",
			"Invalid data object received from Honkai: Star Rail account": "Oggetto dati non valido ricevuto dall'account Honkai: Star Rail",
			"No Honkai: Star Rail account can be found with the provided game account": "Nessun account Honkai: Star Rail trovato per l'account di gioco fornito",
			"Logged into ({0}) {1} ({2})": "Accesso effettuato a ({0}) {1} ({2})",
			"Failed to fetch Mimo game info": "Impossibile ottenere le informazioni sul gioco di Mimo",
			"{0} Mimo event not active": "Evento Mimo di {0} non attivo",
			"Failed to fetch Mimo tasks": "Impossibile ottenere le missioni di Mimo",
			"Failed to finish Mimo task": "Impossibile completare la missione di Mimo",
			"Failed to claim Mimo task reward": "Impossibile riscuotere la ricompensa della missione di Mimo",
			"Failed to fetch Mimo shop items": "Impossibile ottenere gli oggetti del negozio di Mimo",
			"Failed to match Mimo shop items": "Impossibile associare gli oggetti del negozio di Mimo",
			"Failed to fetch Mimo shop purchases": "Impossibile ottenere gli acquisti nel negozio di Mimo",
			"Mimo event has ended": "L'evento Mimo è terminato",
			"Mimo automation is already running for this account": "L'automazione di Mimo è già in esecuzione per questo account",
			"({0}) Exchanged {1}": "({0}) Scambiato {1}",
			"({0}) Failed to load Mimo shop policy snapshot: {1}": "({0}) Impossibile caricare lo stato della politica del negozio di Mimo: {1}",
			"({0}) Failed to save Mimo shop policy snapshot: {1}": "({0}) Impossibile salvare lo stato della politica del negozio di Mimo: {1}",
			"({0}) Inventory duration detected: {1} -> {2}": "({0}) Durata dell'inventario rilevata: {1} -> {2}",
			"({0}) Shop purchase history unavailable. Reserving points for unconfirmed rewards.": "({0}) Cronologia degli acquisti nel negozio non disponibile. Punti riservati per le ricompense non confermate.",
			"({0}) New inventory detected. Rebuilt Mimo shop plan (always={1}, guaranteed={2}, lotteryReserve={3})": "({0}) Nuovo inventario rilevato. Piano del negozio di Mimo ricostruito (always={1}, guaranteed={2}, lotteryReserve={3})",
			"({0}) Inventory unchanged. Mimo budget: always={1}, guaranteed={2}, lotteryReserve={3}": "({0}) Inventario invariato. Budget di Mimo: always={1}, guaranteed={2}, lotteryReserve={3}",
			"({0}) Shop data unavailable. Using cached Mimo thresholds: threshold1={1}, threshold2={2}": "({0}) Dati del negozio non disponibili. Uso delle soglie di Mimo nella cache: threshold1={1}, threshold2={2}",
			"({0}) Shop data unavailable and no compatible cached snapshot found. Lottery paused to protect guaranteed rewards.": "({0}) Dati del negozio non disponibili e nessuno stato compatibile trovato nella cache. Lotteria sospesa per proteggere le ricompense garantite.",
			"({0}) Budget breakdown (source={1}): staticFloor={2}, alwaysReserve={3}, lotteryReserve={4}, pointsAvailableForConditional={5}, pointsAvailableForLottery={6}": "({0}) Dettaglio del budget (source={1}): staticFloor={2}, alwaysReserve={3}, lotteryReserve={4}, pointsAvailableForConditional={5}, pointsAvailableForLottery={6}",
			"({0}) Lottery budget: surplus={1}, drawsRemainingToday={2}, drawsBeforeSeasonEnd={3}": "({0}) Budget della lotteria: surplus={1}, drawsRemainingToday={2}, drawsBeforeSeasonEnd={3}",
			"({0}) Daily lottery limit cannot spend the current surplus before season end: at least {1} points remain even without point rebates or future earnings.": "({0}) Il limite giornaliero della lotteria impedisce di spendere il surplus attuale prima della fine della stagione: rimangono almeno {1} punti anche senza rimborsi di punti o guadagni futuri.",
			"Failed to exchange Mimo item": "Impossibile scambiare l'oggetto di Mimo",
			"Failed to fetch Mimo lottery info": "Impossibile ottenere le informazioni sulla lotteria di Mimo",
			"Failed to draw lottery": "Estrazione della lotteria non riuscita",
			"Failed to get Mimo game info": "Impossibile ottenere le informazioni sul gioco di Mimo",
			"({0}) Starting Mimo automation - Current points: {1}": "({0}) Avvio dell'automazione di Mimo - Punti attuali: {1}",
			"({0}) Exchanged {1} for code: {2}": "({0}) Scambiato {1} per il codice: {2}",
			"({0}) Lottery draw: {1}": "({0}) Estrazione della lotteria: {1}",
			"({0}) Redeemed lottery code: {1}": "({0}) Codice della lotteria riscattato: {1}",
			"Failed to redeem lottery code {0}: {1}": "Riscatto del codice della lotteria {0} non riuscito: {1}",
			"No {0} items found": "Nessun oggetto {0} trovato",
			"Cache hit for key: {0} (keyv)": "Chiave trovata nella cache: {0} (keyv)",
			"Cache miss for key: {0}": "Chiave non trovata nella cache: {0}",
			"An error while getting the key": "Errore durante il recupero della chiave",
			"Invalidated cache for key: {0}": "Cache invalidata per la chiave: {0}",
			"Error invalidating cache for key {0}: {1}": "Errore durante l'invalidazione della cache per la chiave {0}: {1}",
			"Failed to fetch diary data": "Impossibile ottenere i dati del diario",
			"Daily Activity": "Attività giornaliera",
			"Pure Fiction": "Pura finzione",
			"Rate limited, retrying in {0}s... (attempt {1}/{2})": "Limite di richieste raggiunto, nuovo tentativo tra {0}s... (tentativo {1}/{2})",
			"Failed to fetch data from hoyolab": "Impossibile ottenere dati da HoYoLAB",
			"HoyoLab returned non-zero retcode": "HoYoLAB ha restituito un retcode diverso da zero",
			"Request threw non-200 status code": "La richiesta ha restituito un codice di stato diverso da 200",
			"Failed to redeem code": "Riscatto del codice non riuscito",
			"({0}) {1} redeemed code: {2}": "({0}) {1} codice riscattato: {2}",
			"Request failed ({0} {1}) code={2} after {3} retries": "Richiesta non riuscita ({0} {1}) code={2} dopo {3} tentativi",
			"You have successfully checked in today, Captain~": "Check-in di oggi completato, Capitano~",
			"You've already checked in today, Captain~": "Hai già effettuato il check-in oggi, Capitano~",
			"No HoyoLab ID provided for Honkai Impact controller": "Nessun ID HoYoLAB fornito per il controller Honkai Impact",
			"No Honkai Impact accounts provided": "Nessun account Honkai Impact fornito",
			"Failed to login to Honkai Impact account": "Accesso all'account Honkai Impact non riuscito",
			"Invalid data object received from Honkai Impact account": "Oggetto dati non valido ricevuto dall'account Honkai Impact",
			"No Honkai Impact account can be found with the provided game account": "Nessun account Honkai Impact trovato per l'account di gioco fornito",
			"No active accounts found for Honkai Impact": "Nessun account attivo trovato per Honkai Impact",
			"No data received from API": "Nessun dato ricevuto dall'API",
			"Not Completed": "Non completato",
			"No necessary data was received from hoyolab": "I dati necessari non sono stati ricevuti da HoYoLAB",
			"No active accounts found for Zenless Zone Zero": "Nessun account attivo trovato per Zenless Zone Zero",
			"Congratulations Proxy! You have successfully checked in today!~": "Congratulazioni, Proxy! Hai effettuato il check-in di oggi!~",
			"You have already checked in today, Proxy!~": "Hai già effettuato il check-in oggi, Proxy!~",
			"No game ID provided for ZenlessZoneZero.": "Nessun ID gioco fornito per ZenlessZoneZero.",
			"No ZenlessZoneZero account data provided.": "Nessun dato account ZenlessZoneZero fornito.",
			"Failed to login to Zenless Zone Zero account": "Accesso all'account Zenless Zone Zero non riuscito",
			"Invalid data object received from Zenless Zone Zero account": "Oggetto dati non valido ricevuto dall'account Zenless Zone Zero",
			"No Zenless Zone Zero account can be found with the provided game account": "Nessun account Zenless Zone Zero trovato per l'account di gioco fornito",
			"Daily Commission": "Incarichi giornalieri",
			"Spiral Abyss": "Abisso a spirale",
			"Hoyolab API returned non-200 status code": "L'API HoYoLAB ha restituito un codice di stato diverso da 200",
			"Hoyolab API returned non-zero retcode": "L'API HoYoLAB ha restituito un retcode diverso da zero",
			"No active accounts found for Genshin Impact": "Nessun account attivo trovato per Genshin Impact",
			"Congratulations, Traveler! You have successfully checked in today~": "Congratulazioni, Viaggiatore! Hai effettuato il check-in di oggi~",
			"Traveler, you've already checked in today~": "Viaggiatore, hai già effettuato il check-in oggi~",
			"No HoyoLab ID provided for Genshin controller": "Nessun ID HoYoLAB fornito per il controller Genshin",
			"No Genshin accounts provided": "Nessun account Genshin fornito",
			"Failed to login to Genshin account": "Accesso all'account Genshin non riuscito",
			"Invalid data object received from Genshin account": "Oggetto dati non valido ricevuto dall'account Genshin",
			"No Genshin account can be found with the provided game account": "Nessun account Genshin trovato per l'account di gioco fornito",
			"Code redeemed successfully!": "Codice riscattato!",
			Expedition: "Spedizione",
			Username: "Nome utente",
			Region: "Regione",
			Rank: "Livello",
			Result: "Risultato",
			None: "Nessuno",
			Dailies: "Attività giornaliere",
			Weeklies: "Attività settimanali",
			Stamina: "Energia",
			Status: "Stato",
			Platform: "Piattaforma",
			Manual: "Manuale",
			Unknown: "Sconosciuto",
			Mail: "Posta",
			Others: "Altro",
			Event: "Evento",
			Other: "Altro",
			Completed: "Completato",
			Finished: "Terminato",
			Closed: "Chiuso",
			Open: "Aperto",
			Ongoing: "In corso",
			"Your account is currently encountered with a captcha challenge. Please solve the captcha by visiting the following link to solve the challenge: {0}": "Il tuo account ha ricevuto una richiesta captcha. Risolvila visitando il seguente link: {0}",
			"(false by default)": "(disabilitato per impostazione predefinita)",
			Accounts: "Account",
			"Add Genshin Impact accounts": "Aggiungi account Genshin Impact",
			"Add Honkai Impact 3rd accounts": "Aggiungi account Honkai Impact 3rd",
			"Add Honkai: Star Rail accounts": "Aggiungi account Honkai: Star Rail",
			"Add Tears of Themis accounts": "Aggiungi account Tears of Themis",
			"Add Zenless Zone Zero accounts": "Aggiungi account Zenless Zone Zero",
			"Check:": "Controllo:",
			"Config.json5 Generator": "Generatore di config.json5",
			"Cookie:": "Cookie:",
			Crons: "Attività pianificate",
			"DailiesCheck:": "Controllo attività giornaliere:",
			"Disable Telegram Notification:": "Disabilita avvisi Telegram:",
			"Discord Bot": "Bot Discord",
			"Discord Bot ID:": "ID del bot Discord:",
			"Discord Bot Token:": "Token del bot Discord:",
			"Discord Bot:": "Bot Discord:",
			"Discord User ID:": "ID utente Discord:",
			"Discord Webhook": "Webhook Discord",
			"Discord Webhook:": "Webhook Discord:",
			"Discord:": "Discord:",
			"Enable test notification on startup:": "Abilita la notifica di prova all'avvio:",
			"Enable this if you want to automatically redeem codes": "Abilita per riscattare automaticamente i codici",
			"Enable this if you want to get notified when your expedition is done (false by default)": "Abilita per ricevere una notifica quando la spedizione è completata (disabilitato per impostazione predefinita)",
			"Enable this if you want to get notified when your stamina is above the threshold (false by default)": "Abilita per ricevere una notifica quando l'energia supera la soglia (disabilitato per impostazione predefinita)",
			"Enable this if you want to get reminded to do your daily commissions (false by default)": "Abilita il promemoria degli incarichi giornalieri (disabilitato per impostazione predefinita)",
			"Enable this if you want to get reminded to do your daily tasks (false by default)": "Abilita il promemoria delle attività giornaliere (disabilitato per impostazione predefinita)",
			"Enable this if you want to get reminded to do your weeklies (false by default)": "Abilita il promemoria delle attività settimanali (disabilitato per impostazione predefinita)",
			"Enable this if you want to get reminded to do your weekly tasks (false by default)": "Abilita il promemoria delle attività settimanali (disabilitato per impostazione predefinita)",
			"Expedition:": "Spedizioni:",
			"Generate and Download config.json5": "Genera e scarica config.json5",
			"Genshin Impact Active:": "Genshin Impact attivo:",
			"Genshin Impact Cookie:": "Cookie Genshin Impact:",
			"Genshin Impact accounts {0}": "Account Genshin Impact {0}",
			"HoYoLAB locale:": "Lingua HoYoLAB:",
			"Honkai Impact 3rd Active:": "Honkai Impact 3rd attivo:",
			"Honkai Impact 3rd accounts {0}": "Account Honkai Impact 3rd {0}",
			"Honkai: Star Rail Active:": "Honkai: Star Rail attivo:",
			"Honkai: Star Rail Cookie:": "Cookie Honkai: Star Rail:",
			"Honkai: Star Rail accounts {0}": "Account Honkai: Star Rail {0}",
			"If you have same account for both genshin and starrail": "Se usi lo stesso account per Genshin e Star Rail",
			"Import Config": "Importa configurazione",
			"Import Existing Config": "Importa una configurazione esistente",
			"Just add another object inside the data array": "Aggiungi un altro oggetto nell'array data",
			Language: "Lingua",
			"Log Level:": "Livello di log:",
			"Persistent:": "Ripeti notifiche:",
			Platforms: "Piattaforme",
			"Please note that if you have one account with characters in multiple servers": "Se hai un account con personaggi su più server",
			"Realm:": "Regno:",
			"Same goes for any other game that will be supported in the future": "Lo stesso vale per gli altri giochi che saranno supportati in futuro",
			"Select config.json5 file:": "Seleziona il file config.json5:",
			"Select log level": "Seleziona il livello di log",
			"Select option": "Seleziona un'opzione",
			"Set to false if you don't want to receive test notifications on startup": "Disabilita se non vuoi ricevere notifiche di prova all'avvio",
			"Set to true if you want to disable notification for Telegram bot (sounds, vibration, etc.)(false by default)": "Abilita per silenziare le notifiche del bot Telegram (suoni, vibrazione, ecc.) (disabilitato per impostazione predefinita)",
			"Set to true if you want to enable Genshin Impact (false by default)": "Abilita per attivare Genshin Impact (disabilitato per impostazione predefinita)",
			"Set to true if you want to enable Honkai Impact 3rd (false by default)": "Abilita per attivare Honkai Impact 3rd (disabilitato per impostazione predefinita)",
			"Set to true if you want to enable Honkai: Star Rail (false by default)": "Abilita per attivare Honkai: Star Rail (disabilitato per impostazione predefinita)",
			"Set to true if you want to enable Tears of Themis (false by default)": "Abilita per attivare Tears of Themis (disabilitato per impostazione predefinita)",
			"Set to true if you want to enable Telegram bot (false by default)": "Abilita per attivare il bot Telegram (disabilitato per impostazione predefinita)",
			"Set to true if you want to enable Zenless Zone Zero (false by default)": "Abilita per attivare Zenless Zone Zero (disabilitato per impostazione predefinita)",
			"Set to true if you want to get notified every time your expedition is done (false by default)": "Abilita per ricevere notifiche ripetute quando la spedizione è completata (disabilitato per impostazione predefinita)",
			"Set to true if you want to get notified every time your stamina is above the threshold (false by default)": "Abilita per ricevere notifiche ripetute quando l'energia supera la soglia (disabilitato per impostazione predefinita)",
			"Set to true if you want to send notification to Discord webhook(false by default)": "Abilita per inviare notifiche al webhook Discord (disabilitato per impostazione predefinita)",
			"Stamina Check:": "Controllo energia:",
			"Stamina Persistent:": "Ripeti notifiche energia:",
			"Stamina Threshold:": "Soglia energia:",
			"Stamina:": "Energia:",
			"Support multi-account for every type of game": "Supporta più account per ogni gioco",
			"Tears of Themis Active:": "Tears of Themis attivo:",
			"Tears of Themis accounts {0}": "Account Tears of Themis {0}",
			"Telegram Bot": "Bot Telegram",
			"Telegram Bot Token:": "Token del bot Telegram:",
			"Telegram Bot:": "Bot Telegram:",
			"Telegram Chat ID:": "ID chat Telegram:",
			"Test Notification": "Notifica di prova",
			"This platform is optional, only use this if you have want to access commands via Discord bot": "Questa piattaforma è facoltativa: usala solo se vuoi accedere ai comandi tramite un bot Discord",
			"This will check if your shop has finished selling videos (false by default)": "Controlla se il negozio ha finito di vendere video (disabilitato per impostazione predefinita)",
			"Threshold:": "Soglia:",
			"Toggle Dark Mode": "Attiva/disattiva tema scuro",
			"Use a lowercase locale, such as en-us or it-it.": "Usa una lingua in minuscolo, ad esempio en-us o it-it.",
			"User Agent:": "User Agent:",
			"User ID:": "ID utente:",
			"Webhook URL:": "URL webhook:",
			"You can blacklist some crons if you don't want to run them (empty by default)": "Puoi escludere alcune attività pianificate usando la blacklist (vuota per impostazione predefinita)",
			"You can copy the cookie values from the genshin account": "Puoi copiare i valori dei cookie dall'account Genshin",
			"You can follow this guide to create a bot: https://github.com/torikushiii/hoyolab-auto/blob/main/setup/TELEGRAM.md": "Puoi seguire questa guida per creare un bot: https://github.com/torikushiii/hoyolab-auto/blob/main/setup/TELEGRAM.md",
			"You can follow this guide to create a webhook: https://github.com/torikushiii/hoyolab-auto/blob/main/setup/DISCORD_WEBHOOK.md": "Puoi seguire questa guida per creare un webhook: https://github.com/torikushiii/hoyolab-auto/blob/main/setup/DISCORD_WEBHOOK.md",
			"You can use this site to generate cron expression: https://crontab.guru/": "Puoi usare questo sito per generare espressioni cron: https://crontab.guru/",
			"You can whitelist some crons if you only want to run specific crons(empty by default)": "Puoi usare la whitelist per eseguire solo determinate attività pianificate (vuota per impostazione predefinita)",
			"Your Discord bot ID": "L'ID del tuo bot Discord",
			"Your Discord user ID to ping you when to do your dailies/weeklies": "Il tuo ID utente Discord per ricevere menzioni per le attività giornaliere e settimanali",
			"Your Discord user ID to ping you when to do your dailies/weeklies or when your stamina is above the threshold and your expedition is done. This is optional, you can leave it as null if you don't want to get pinged.": "Il tuo ID utente Discord per ricevere menzioni per le attività giornaliere e settimanali, l'energia sopra soglia e le spedizioni completate. È facoltativo: lascia null se non vuoi ricevere menzioni.",
			"Your stamina threshold, only fires notification when your stamina is above this value (150 by default)": "La soglia di energia: invia notifiche solo quando l'energia supera questo valore (150 per impostazione predefinita)",
			"Zenless Zone Zero Active:": "Zenless Zone Zero attivo:",
			"Zenless Zone Zero Cookie:": "Cookie Zenless Zone Zero:",
			"Zenless Zone Zero accounts {0}": "Account Zenless Zone Zero {0}",
			"blacklist:": "Attività escluse:",
			"checkIn:": "Check-in:",
			"codeRedeem:": "Riscatto codici:",
			"created by": "creato da",
			error: "errore",
			"expedition:": "Spedizioni:",
			false: "disabilitato",
			"false by default": "disabilitato per impostazione predefinita",
			info: "informazioni",
			"missedCheckIn:": "Check-in mancati:",
			"or when your stamina is above the threshold and your expedition is done": "oppure quando l'energia supera la soglia e la spedizione è completata",
			"persistent:": "Ripeti notifiche:",
			"realmCurrency:": "Valuta del regno:",
			"redeemCode:": "Riscatto codici:",
			"shopStatus:": "Stato del negozio:",
			"so please be careful when enabling this, and only enable it on the account that you want to redeem the code": "Abilita questa opzione solo sull'account per cui vuoi riscattare il codice",
			"stamina:": "Energia:",
			"the code will be redeemed but you won't get the reward": "il codice verrà riscattato ma non riceverai la ricompensa",
			"this is optional, you can leave it as null if you don't want to get pinged": "È facoltativo: lascia null se non vuoi ricevere menzioni",
			"threshold:": "Soglia:",
			true: "abilitato",
			"userId:": "ID utente:",
			warn: "avviso",
			"weekliesCheck:": "Controllo attività settimanali:",
			"whitelist:": "Attività consentite:",
			"| source code:": "| codice sorgente:",
			"Please select a config.json5 file.": "Seleziona un file config.json5.",
			"Failed to import configuration.": "Importazione della configurazione non riuscita.",
			"Unable to read the selected file.": "Impossibile leggere il file selezionato.",
			"The selected file is empty.": "Il file selezionato è vuoto.",
			"Failed to parse configuration: {0}": "Impossibile interpretare la configurazione: {0}",
			"Config imported successfully.": "Configurazione importata.",
			"Invalid configuration file.": "File di configurazione non valido.",
			Delete: "Elimina",
			"Application and HoYoLAB language:": "Lingua del software e di HoYoLAB:",
			"Redeemed codes for all games have been reset.": "I codici riscattati sono stati azzerati per tutti i giochi.",
			"All stored redeemed codes have been reset.": "Tutti i codici riscattati memorizzati sono stati azzerati.",
			"All redeemed codes:": "Tutti i codici riscattati:",
			"Code Redemption Paused - HoYoLAB Login Expired": "Riscatto dei codici sospeso - accesso a HoYoLAB scaduto",
			"Update your HoYoLAB cookie or restore automatic cookie refresh. Pending codes will be retried after the cookie is renewed.": "Aggiorna il cookie di HoYoLAB o ripristina il rinnovo automatico. I codici in sospeso verranno riprovati dopo il rinnovo del cookie.",
			"ZZZ Daily Lottery": "Lotteria giornaliera ZZZ",
			"🎲 ZZZ Daily Lottery": "🎲 Lotteria giornaliera ZZZ",
			"You haven't claimed your daily lottery reward yet!": "Non hai ancora ritirato la ricompensa della lotteria giornaliera!",
			"Reminds you if you haven't claimed the ZZZ daily lottery reward.": "Ti ricorda se non hai ritirato la ricompensa della lotteria giornaliera di ZZZ.",
			"This is a test notification to confirm that {0} is working properly.": "Questa è una notifica di prova per verificare che {0} funzioni correttamente.",
			"Dailies reminder hour:": "Ora del promemoria attività giornaliere:",
			"Dailies reminder minute:": "Minuto del promemoria attività giornaliere:",
			"Dailies reminder timezone (optional):": "Fuso orario del promemoria attività giornaliere (facoltativo):",
			"Leave blank to use game server time. Use an IANA timezone for daylight-saving changes.": "Lascia vuoto per usare l'orario del server di gioco. Usa un fuso orario IANA per gestire l'ora legale.",
			"No {0} accounts provided. Skipping...": "Nessun account {0} fornito. Operazione ignorata...",
			"No active accounts found for {0}": "Nessun account attivo trovato per {0}",
			"Failed to login to {0} account: {1}": "Accesso all'account {0} non riuscito: {1}",
			"No {0} account found for ltuid: {1}": "Nessun account {0} trovato per ltuid: {1}",
			"Error: {0}": "Errore: {0}",
			"Failed to sign in.": "Check-in non riuscito.",
			"Failed to get sign info.": "Impossibile ottenere le informazioni sul check-in.",
			"Failed to get awards data.": "Impossibile ottenere i dati delle ricompense.",
			"No awards data available.": "Nessun dato sulle ricompense disponibile.",
			"Code {0} already redeemed for {1}": "Codice {0} già riscattato per {1}",
			"Attempting to redeem code {0} for {1}": "Tentativo di riscatto del codice {0} per {1}",
			"Completed forced code redemption for {0}": "Riscatto forzato dei codici completato per {0}",
			"Unknown game: {0}": "Gioco sconosciuto: {0}",
			"Code {0} redemption for {1} returned status {2}": "Il riscatto del codice {0} per {1} ha restituito lo stato {2}",
			"Request failed with status {0}": "Richiesta non riuscita con stato {0}",
			"Authentication error for code {0} in {1}: {2}. Try logging in via incognito mode and get a fresh cookie from there.": "Errore di autenticazione per il codice {0} in {1}: {2}. Prova ad accedere in modalità incognito e a ottenere un nuovo cookie.",
			"Code {0} redemption failed for {1}:": "Riscatto del codice {0} per {1} non riuscito:",
			"Unknown error (retcode {0})": "Errore sconosciuto (retcode {0})",
			"Code {0} successfully redeemed for {1}:": "Codice {0} riscattato per {1}:",
			"Error redeeming code {0} for {1}:": "Errore durante il riscatto del codice {0} per {1}:",
			"Unknown region {0} for game {1}": "Regione {0} sconosciuta per il gioco {1}",
			"Successful check-ins for {0}:": "Check-in completati per {0}:",
			"Successful check-ins for {0}: {1}": "Check-in completati per {0}: {1}",
			"Code redemption is disabled in config for {0}": "Il riscatto dei codici è disabilitato nella configurazione per {0}",
			"An error occurred during {0} check-in:": "Si è verificato un errore durante il check-in di {0}:",
			"{0} Daily Check-In": "Check-in giornaliero {0}",
			"Total Check-Ins": "Check-in totali",
			"Discord webhook failed": "Invio al webhook Discord non riuscito",
			"Discord rate limited (attempt {0}/{1}), waiting {2}ms": "Limite di richieste Discord raggiunto (tentativo {0}/{1}), attesa di {2}ms",
			"Discord webhook gave up after repeated 429 responses.": "Invio al webhook Discord interrotto dopo ripetute risposte 429.",
			"\n…and {0} more": "\n…e altri {0}",
			"Redeemed ({0})": "Riscattati ({0})",
			"Failed ({0})": "Non riusciti ({0})",
			"{0} Code Redemption": "Riscatto codici {0}",
			"All games checked in successfully": "Check-in completato per tutti i giochi",
			"Error during check-in process:": "Errore durante il check-in:",
			"Invalid game name: {0}. Must be one of: genshin, honkai, starrail, zenless": "Nome del gioco non valido: {0}. Deve essere uno tra: genshin, honkai, starrail, zenless",
			"Invalid game name: {0}": "Nome del gioco non valido: {0}",
			"Code redemption is not supported for Honkai Impact 3rd": "Il riscatto dei codici non è supportato per Honkai Impact 3rd",
			"Code redemption is disabled in config for {0}. Use forceRedeem=true to bypass.": "Il riscatto dei codici è disabilitato nella configurazione per {0}. Usa forceRedeem=true per forzarlo.",
			"Code redemption is disabled in config": "Il riscatto dei codici è disabilitato nella configurazione",
			"No {0} accounts provided. Cannot redeem codes.": "Nessun account {0} fornito. Impossibile riscattare i codici.",
			"No {0} accounts provided": "Nessun account {0} fornito",
			"Failed to get account details for {0}": "Impossibile ottenere i dettagli dell'account per {0}",
			"Redeeming codes for {0} account: {1} ({2})": "Riscatto dei codici per l'account {0}: {1} ({2})",
			"Force redeemed all codes for {0} ({1})": "Riscatto forzato di tutti i codici per {0} ({1}) completato",
			"Redeemed new codes for {0} ({1})": "Nuovi codici riscattati per {0} ({1})",
			"Error redeeming codes for {0}:": "Errore durante il riscatto dei codici per {0}:",
			Nickname: "Soprannome",
			"source code:": "codice sorgente:",
			"destroy() is not implemented": "destroy() non è implementato"
		}
	};
	if (typeof module === "object" && module.exports) {
		module.exports = catalog;
	}
	else {
		root.HoyoLabLocales = root.HoyoLabLocales ?? {};
		root.HoyoLabLocales[catalog.language] = catalog;
		root.HoyoLabI18n?.registerCatalog(catalog);
	}
})(globalThis);
